### ISSUE TITLE
Unknown output?

### ISSUE THREAD

**Issue by tejasnayak25** [namdevel/anime-ai#1]
I tried implementing this into my project but the output I get is only this "Create anime... Curl error: Complete...". 
It gives a black image(only a black background)
What next?

**Comment by namtxs** [comment]
Try downloading the code again. I have changed the URL with new working endpoint.

**Comment by tejasnayak25** [comment]
What are its limitations? How many requests can it handle?

**Comment by namtxs** [comment]
IDK, untested

**Comment by tejasnayak25** [comment]
Thank you

**Comment by tejasnayak25** [comment]
Sorry but its still black
![ToonApp](https://user-images.githubusercontent.com/101463222/225857537-dc534031-1cd1-4f6a-a21c-557aa11284ed.jpg)

**Comment by namtxs** [comment]
the image must contain face
